## GROUP NO :- 16

### TOPIC :- CREATE A NUMPY LIBRARY WITH ALL IT'S METHODS AND FUNCTION

***ARRAY KEY FEATURES***

1. Homogeneous: All elements in an array have the same data type (e.g., integers, floats, strings).
2. Fixed-size: Arrays have a fixed number of elements.
3. Contiguous memory: Elements are stored next to each other in memory.
4. Indexed: Elements can be accessed using indices (e.g., arr[0]).


### Numpy:-

In [6]:
# numpy ---> numerical cal, arry operation, stats calculation

In [8]:
!pip install numpy

In [9]:
import numpy as np

In [10]:
l= [1,25,38,40]

In [11]:
type(l)

list

In [12]:
x = np.array([1,25,38,40])  # --> Step to create a numpy array

In [13]:
y = np.array(x)

In [14]:
y

array([ 1, 25, 38, 40])

In [15]:
type(y)

numpy.ndarray

In [16]:
y.ndim   #---> .ndim method is used to check the dimension of array

1

In [17]:
y

array([ 1, 25, 38, 40])

In [18]:
y.dtype

dtype('int32')

In [19]:
np.array([10,25,50.5],dtype=int)

array([10, 25, 50])

In [21]:
np.array([10,25,50.5],dtype=int,ndmin=2)

array([[10, 25, 50]])

In [22]:
np.array([10,25,50.5],dtype=int,ndmin=2).ndim

2

In [54]:
np.array([10,25,50.5],complex,ndmin=2)  #--> complex is used to change from integer datatype to complex datatype

array([[10. +0.j, 25. +0.j, 50.5+0.j]])

In [25]:
l = [1,25,38,'hello',40]

In [26]:
l

[1, 25, 38, 'hello', 40]

In [27]:
np.array(l,ndmin = 3)

array([[['1', '25', '38', 'hello', '40']]], dtype='<U11')

In [28]:
np.array([[12,35,67],[8,9,10],[89,67,90]])

array([[12, 35, 67],
       [ 8,  9, 10],
       [89, 67, 90]])

In [30]:
np.array([[12,35,67],[8,9,10],[89,67,90]],float).ndim

2

In [31]:
type(np.array([[12,35,67],[8,9,10],[89,67,90]]))

numpy.ndarray

##### *** Array creation : Conversion from other python structure. (etc: list,tuples)***

In [34]:
listarry = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [35]:
listarry

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [36]:
listarry.dtype

dtype('int32')

In [58]:
listarry.shape

(3, 3)

In [62]:
listarry.size

9

In [63]:
listarry[0,1]= '69'

In [67]:
listarry

array([[ 1, 69,  3],
       [ 5,  8,  5],
       [ 0,  3,  1]])

In [69]:
listarry*2

array([[  2, 138,   6],
       [ 10,  16,  10],
       [  0,   6,   2]])

In [71]:
listarry%2==0

array([[False, False, False],
       [False,  True, False],
       [ True, False, False]])

In [73]:
listarry[listarry%2==0]

array([8, 0])

### ARRAY CREATION

##### ***Aranges,zeros,ones,etc ***

 1.] np.arange()

Definition: Create an array with evenly spaced values within a specified range.

Syntax: np.arange(start, stop, step, dtype=None)


In [79]:
my_array = np.arange(1, 6)
print(my_array)  # [1 2 3 4 5]


[1 2 3 4 5]


In [81]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [83]:
l = np.arange(1,7)

In [85]:
l

array([1, 2, 3, 4, 5, 6])

2.]  np.zeros()

Definition: Create an array filled with zeros.

Syntax: np.zeros(shape, dtype=float)


In [89]:
a = np.zeros(5)
print(a)  # [0. 0. 0. 0. 0.]


[0. 0. 0. 0. 0.]


In [91]:
b =np.zeros((2,3))

In [93]:
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [95]:
np.zeros((3,4),dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [97]:
np.zeros((3,4),dtype =float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [99]:
np.zeros((3,4),dtype =complex)

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

3.] np.ones()

Definition: Create an array filled with ones.

Syntax: np.ones(shape, dtype=float, order='C')



In [104]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

4.]  np.linspace()

Definition: Create an array with evenly spaced values over a specified range.

Syntax: np.linspace(start, stop, num, endpoint=True, retstep=False, dtype=None)


In [109]:

my_array = np.linspace(1, 5, 5)
print(my_array)  # [1. 2. 3. 4. 5.]


[1. 2. 3. 4. 5.]


In [111]:
np.linspace(1,10,4)

array([ 1.,  4.,  7., 10.])


5. np.full()

Definition: Create an array filled with a specified value.

Syntax: np.full(shape, fill_value, dtype=None)


In [115]:
my_array = np.full(5, 7)
print(my_array)  # [7 7 7 7 7]


[7 7 7 7 7]


In [117]:
np.full(9,1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

6]. np.reshape

Definition: Changes the shape of an array without changing its data


Syntax: np.reshape(arr, newshape, order='C')



In [123]:
b = 1,2,3,4,5,6,7,8

In [125]:
np.reshape(b,(2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [127]:
x = [0,1,2,3,4,5]

In [129]:
np.reshape(x,(2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [131]:
np.reshape(x,(3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

In [133]:
np.reshape(x,(6,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])


7. *np.random.rand()*

Syntax: np.random.rand(d0, d1, ..., dn)

Definition: Creates a NumPy array with random values.


In [6]:
import numpy as np
arr = np.random.rand(5)


In [8]:
print(arr)

[0.7261336  0.52612826 0.50163487 0.58156479 0.21628712]


8]. *np.random.randn()*

Syntax: np.random.randn(d0, d1, ..., dn)

Definition: Creates a NumPy array with random values from a normal distribution.

In [11]:
import numpy as np
arr = np.random.randn(5)


In [13]:
print(arr)


[-0.34059047  0.40861255  0.08179213 -1.34714177  1.13261411]


## INDEXING AND SLICING


In [5]:
import numpy as np

In [7]:
x = np.array([[12,35,67],[8,9,10],[89,67,90]])

In [9]:
x

array([[12, 35, 67],
       [ 8,  9, 10],
       [89, 67, 90]])

In [11]:
x[1,0]

8

In [13]:
x [1][0]

8

In [15]:
x[0][1:3]

array([35, 67])

In [17]:
x[1:3,1]         

array([ 9, 67])

In [19]:
x[0:2,0:2]

array([[12, 35],
       [ 8,  9]])

## Comparision of Numpy over List

### Basic Mathematical Operations.


In [22]:
l1 =[1,2,3,4,5]
l2 =[6,7,8,9,10]

In [24]:
np.array(l1)+np.array(l2)

array([ 7,  9, 11, 13, 15])

In [26]:
l2[2]=90

In [28]:
l2

[6, 7, 90, 9, 10]

In [31]:
l3 =np.array([1,2,3,4,5])
l4 =np.array([6,7,8,9,10])

In [33]:
print(l4-l3)

[5 5 5 5 5]


In [149]:
y = np.array([[12,3,4],[45,89,90],[11,34,56]])

In [151]:
y

array([[12,  3,  4],
       [45, 89, 90],
       [11, 34, 56]])

In [152]:
y.min()

3

In [153]:
y.max()

90

In [154]:
np.exp(y)

array([[1.62754791e+05, 2.00855369e+01, 5.45981500e+01],
       [3.49342711e+19, 4.48961282e+38, 1.22040329e+39],
       [5.98741417e+04, 5.83461743e+14, 2.09165950e+24]])

In [155]:
np.sqrt(y)

array([[3.46410162, 1.73205081, 2.        ],
       [6.70820393, 9.43398113, 9.48683298],
       [3.31662479, 5.83095189, 7.48331477]])

In [156]:
np.log(y)

array([[2.48490665, 1.09861229, 1.38629436],
       [3.80666249, 4.48863637, 4.49980967],
       [2.39789527, 3.52636052, 4.02535169]])

### STATICAL FUNCTION


##### ***Mean,Meadian and Standard Deviation*** 

In [42]:
import numpy as np

In [44]:
# Create an array
arr = np.array([1, 2, 3, 4, 5])

In [46]:
# Calculate mean
mean = np.mean(arr)    #-->Mean: np.mean()  -Calculates the arithmetic mean of an array.                    
print(mean           

3.0


In [48]:
# Calculate median
median = np.median(arr)   #--> Median: np.median() -- Calculates the median (middle value) of an array.
print(median)

3.0


In [50]:
# Calculate standard deviation
std_dev = np.std(arr)   # --> Standard Deviation: np.std() - Calculates the standard deviation of an array.
print(std_dev)

1.4142135623730951


### Linear Algebra Functions

##### ***1.Matrix Multiplication ,2.Matrix Transpose ,3.Matrix Determinant ,4.Matrix Inverse***

##### ***1. Matrix Multiplication***

Matrix multiplication is a fundamental operation in linear algebra. It takes two matrices as input and produces another matrix as output.

Syntax

np.matmul(A, B)

A and B are the input matrices.


In [61]:
# EXAMPLE 

import numpy as np

# Define two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
C = np.matmul(A, B)

print(C)

[[19 22]
 [43 50]]


##### ***2. Matrix Transpose***

The transpose of a matrix is obtained by interchanging its rows and columns.

Syntax

np.transpose(A)

A is the input matrix.


In [64]:
# Example

import numpy as np

# Define a matrix
A = np.array([[1, 2], [3, 4]])

# Calculate the transpose
B = np.transpose(A)

print(B)


[[1 3]
 [2 4]]


##### ***3. Matrix Determinant***

The determinant of a matrix is a scalar value that can be used to describe the scaling effect of the matrix on a region of space.

Syntax

np.linalg.det(A)

A is the input matrix.


In [67]:
# EXAMPLE

import numpy as np

# Define a matrix
A = np.array([[1, 2], [3, 4]])

# Calculate the determinant
det_A = np.linalg.det(A)

print(det_A)


-2.0000000000000004


##### ***4. Matrix Inverse***

The inverse of a matrix is a matrix that, when multiplied by the original matrix, produces the identity matrix.

Syntax

np.linalg.inv(A)

A is the input matrix.


In [70]:
#Example

import numpy as np

# Define a matrix
A = np.array([[1, 2], [3, 4]])

# Calculate the inverse
A_inv = np.linalg.inv(A)

print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]
